name: Build and upload to PyPI

# Only build and upload when a new release tag is created
# on:
#   push:
#     tags:
#       - "v[0-9]+.[0-9]+.[0-9]+"
#       - "v[0-9]+.[0-9]+.[0-9]+[a-z]+[0-9]+"
# Alternatively, build on every branch push, tag push, and pull request change
on: [push] #, pull_request]

jobs:

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          path: dist/*.tar.gz

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          path: wheelhouse/*.whl
          # Temporary allow overwrite until we use setuptools_scm to
          # generate unique version numbers on every push
          overwrite: true

  upload_pypi:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs: [build_sdist, build_wheels]
    environment:
      name: pypi
      url: https://pypi.org/p/python-casacore
      # For testing, use TestPyPI
      # url: https://test.pypi.org/p/python-casacore
    permissions:
      id-token: write
    # Upload to PyPI on every tag starting with 'v'
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    # Alternatively, to publish when a GitHub Release is created, use the following rule:
    # if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v4
        with:
          # unpacks default artifact into dist/
          # if `name: artifact` is omitted, the action will create extra parent dir
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.8.11
        with:
          # For testing, use TestPyPI
          # repository-url: https://test.pypi.org/legacy/
          skip-existing: true
          verbose: true
