name: Build wheels

on:
  # Only a manual trigger for now
  workflow_dispatch:

env:
  # Install HEAD version of casacore-data because we don't need exact version
  # when compiling python-casacore. This avoids failure if it's not up to date.
  CIBW_BEFORE_ALL_MACOS: >
    brew tap casacore/tap &&
    brew install casacore-data --HEAD &&
    brew install casacore --with-python
  # Support native arm64 and universal2 = Intel + ARM for Apple Silicon
  CIBW_ARCHS_MACOS: "x86_64 arm64"

jobs:
  make_sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build SDist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          name: sdist
          path: dist/*.tar.gz

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.15.0

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./wheelhouse/*.whl
